export const MAIL_QUEUE = 'MAIL_QUEUE';

export const CONFIRM_REGISTRATION = 'CONFIRM_REGISTRATION';

export const GET_MAIL_FORGOT_PW_RESPONSE_TOPIC: string =
  'GET_MAIL_FORGOT_PW_RESPONSE_TOPIC';

export const GET_MAIL_ON_REGISTER_RESPONSE_TOPIC: string =
  'GET_MAIL_ON_REGISTER_RESPONSE_TOPIC';

export const GOOGLE_REDIRECT_URL: string = 'GOOGLE_REDIRECT_URL';

export const NOTI_SERVICE: string = 'NOTI_SERVICE';

export const API_GATEWAY: string = 'API_GATEWAY';
