export const USER_PORT: string = 'USER_PORT';
export const FE_PORT: string = 'FE_PORT';
export const ROOT_USERNAME: string = 'CLVADMIN';
export const REDIS_RESET_PW_MAIL_EXPIRE_TIME: string =
  'REDIS_RESET_PW_MAIL_EXPIRE_TIME';
export const REDIS_NEW_PW_MAIL_EXPIRE_TIME: string =
  'REDIS_NEW_PW_MAIL_EXPIRE_TIME';
export const GOOGLE_REDIRECT_URL: string = 'GOOGLE_REDIRECT_URL';
export const GET_MAILING_RESET_PW_RESPONSE_TOPIC: string =
  'GET_MAILING_RESET_PW_RESPONSE_TOPIC';
export const GET_MAILING_ON_SIGNUP_RESPONSE_TOPIC: string =
  'GET_MAILING_ON_SIGNUP_RESPONSE_TOPIC';
export const NOTIFICATION_SERVICE: string = 'NOTIFICATION_SERVICE';
export const API_GATEWAY: string = 'API_GATEWAY';

export const REDIS_RESET_PW_SESSION: string = 'RESET_PW_SESSION';
export const REDIS_CHANGE_PW_SESSION: string = 'REDIS_CHANGE_PW_SESSION';
