export const GET_ALL_PERMISSIONS: string = 'GET_ALL_PERMISSIONS';

export const UPDATE_PERMISSION_ROLE: string = 'UPDATE_PERMISSION_ROLE';

export const ACTIVATE_BY_EMAIL: string = 'ACTIVATE_BY_EMAIL';

export const RESET_PASSWORD: string = 'RESET_PASSWORD';
