export const GET_MAILING_RESET_PW_RESPONSE_TOPIC: string =
  'GET_MAILING_RESET_PW_RESPONSE_TOPIC';

export const GET_MAILING_ON_SIGNUP_RESPONSE_TOPIC: string =
  'GET_MAILING_ON_SIGNUP_RESPONSE_TOPIC';

export const GOOGLE_REDIRECT_URL: string = 'GOOGLE_REDIRECT_URL';

export const NOTI_SERVICE: string = 'NOTI_SERVICE';

export const API_GATEWAY: string = 'API_GATEWAY';
